name: '🚀 New Feature Proposal'
description: Propose a new feature to be added to krp-sharedmemory-client
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for submitting a feature request!
  - type: textarea
    id: feature-description
    attributes:
      label: Describe your feature
      description: 'A clear and concise description of your feature. If you intend to submit a PR for this issue, tell in the description. Thanks!'
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: 'We could provide following implementation...'
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [Contributing Guidelines](https://github.com/krp-races/krp-sharedmemory-client/blob/main/CONTRIBUTING.md).
          required: true
        - label: Read the [docs](https://github.com/krp-races/krp-sharedmemory-client).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/krp-races/krp-sharedmemory-client/issues) that reports the same bug to avoid creating a duplicate.
          required: true
